// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaneo0wFrkUuP8EVhCg7Bjy7DYuTFfiOo',
    appId: '1:770813834035:web:dc2be1ca8c764e2e278446',
    messagingSenderId: '770813834035',
    projectId: 'latihan-uts-3c3e1',
    authDomain: 'latihan-uts-3c3e1.firebaseapp.com',
    databaseURL: 'https://latihan-uts-3c3e1-default-rtdb.firebaseio.com',
    storageBucket: 'latihan-uts-3c3e1.firebasestorage.app',
    measurementId: 'G-H7MNZD7KT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX6nKwCAN2Fn7JkQnqqoh-y6lLTsV_a0g',
    appId: '1:770813834035:android:d1e247c5ebc7ae87278446',
    messagingSenderId: '770813834035',
    projectId: 'latihan-uts-3c3e1',
    databaseURL: 'https://latihan-uts-3c3e1-default-rtdb.firebaseio.com',
    storageBucket: 'latihan-uts-3c3e1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaneo0wFrkUuP8EVhCg7Bjy7DYuTFfiOo',
    appId: '1:770813834035:web:60e3bb001c31724b278446',
    messagingSenderId: '770813834035',
    projectId: 'latihan-uts-3c3e1',
    authDomain: 'latihan-uts-3c3e1.firebaseapp.com',
    databaseURL: 'https://latihan-uts-3c3e1-default-rtdb.firebaseio.com',
    storageBucket: 'latihan-uts-3c3e1.firebasestorage.app',
    measurementId: 'G-NMEFX8W44G',
  );
}
